"""Helpers/api_request_correlator.py — Conservative API-to-Request Association and Direct Value Matching.

Provides:
- Candidate API-to-request linking based on strict causal and evidence criteria.
- 6 evidence levels: exact_script_and_frame, exact_script_compatible_frame,
  initiator_stack_and_frame, initiator_stack_compatible_frame,
  temporal_only_candidate, unlinked.
- Direct value-to-request matching: exact_value_match, encoded_value_match,
  configured_transformation_match, same_script_subsequent_request, no_value_match.
- Ambiguity and ranking logic.
- Summary metrics distinguishing unique API events and unique requests.
"""

from __future__ import annotations

import base64
import hashlib
import json
from typing import Any
from urllib.parse import quote, quote_plus

# Noise filter: skip common trivial or screen dimension values to avoid false matches
EXCLUDED_VALUES = {
    "true", "false", "null", "undefined", "0", "1", "", "none", "nan",
    "1920", "1080", "800", "600", "1920x1080", "1366x768", "360x640",
    "1440x900", "1536x864", "2560x1440", "width", "height", "get", "set"
}

MIN_VALUE_LENGTH = 5


def match_value_in_text(raw_val: str, text: str) -> str | None:
    """Test if raw_val or its standard encodings appear inside text.
    
    Returns match type ('exact_value_match', 'encoded_value_match',
    'configured_transformation_match') or None.
    """
    if not raw_val or not text or len(raw_val) < MIN_VALUE_LENGTH:
        return None
    if raw_val.lower() in EXCLUDED_VALUES:
        return None

    # 1. Exact string match
    if raw_val in text:
        return "exact_value_match"

    # 2. Encoded matches (URL-encoded, JSON-quoted, Base64)
    url_enc = quote(raw_val)
    if url_enc != raw_val and url_enc in text:
        return "encoded_value_match"

    url_plus = quote_plus(raw_val)
    if url_plus != raw_val and url_plus in text:
        return "encoded_value_match"

    try:
        json_enc = json.dumps(raw_val)
        if json_enc != raw_val and json_enc in text:
            return "encoded_value_match"
    except Exception:
        pass

    try:
        b64_enc = base64.b64encode(raw_val.encode("utf-8")).decode("ascii")
        if len(b64_enc) >= 8 and b64_enc in text:
            return "encoded_value_match"
    except Exception:
        pass

    # 3. Known hash transformations (MD5, SHA1, SHA256)
    payload = raw_val.encode("utf-8", errors="replace")
    md5_hash = hashlib.md5(payload).hexdigest()
    if md5_hash in text:
        return "configured_transformation_match"

    sha1_hash = hashlib.sha1(payload).hexdigest()
    if sha1_hash in text:
        return "configured_transformation_match"

    sha256_hash = hashlib.sha256(payload).hexdigest()
    if sha256_hash in text:
        return "configured_transformation_match"

    return None


test_value_in_text = match_value_in_text
test_value_in_text.__test__ = False


# Automatic browser headers generated by the network stack, not script code
AUTOMATIC_BROWSER_HEADERS = {
    "user-agent",
    "accept",
    "accept-language",
    "accept-encoding",
    "sec-ch-ua",
    "sec-ch-ua-mobile",
    "sec-ch-ua-platform",
    "sec-ch-ua-arch",
    "sec-ch-ua-bitness",
    "sec-ch-ua-full-version-list",
    "sec-ch-ua-model",
    "sec-ch-ua-platform-version",
    "sec-fetch-dest",
    "sec-fetch-mode",
    "sec-fetch-site",
    "sec-fetch-user",
    "upgrade-insecure-requests",
    "connection",
    "host",
    "referer",
    "priority",
    "cookie",
    "origin",
    "dnt",
}


def extract_script_controlled_request_text(req: dict[str, Any]) -> str:
    """Extract strictly script-controlled request components for transmission matching.
    
    Excludes automatic browser headers (User-Agent, Accept, Sec-CH-UA*, etc.)
    and URL host/path components that are not query parameters.
    """
    from urllib.parse import urlparse
    targets: list[str] = []

    # 1. Script-controlled URL query components
    for url_key in ("url", "redirectedTo"):
        u = req.get(url_key)
        if u and isinstance(u, str):
            try:
                parsed = urlparse(u)
                if parsed.query:
                    targets.append(parsed.query)
            except Exception:
                if "?" in u:
                    targets.append(u.split("?", 1)[1])

    # 2. Script-controlled POST/PUT request body
    for body_key in ("postData", "body", "post_data"):
        b = req.get(body_key)
        if b and isinstance(b, str):
            targets.append(b)
        elif b and isinstance(b, (dict, list)):
            try:
                targets.append(json.dumps(b))
            except Exception:
                pass

    body_meta = req.get("bodyMetadata")
    if isinstance(body_meta, dict):
        for k in ("preview", "text", "payload", "sanitized_preview"):
            if body_meta.get(k):
                targets.append(str(body_meta[k]))

    # 3. Script-controlled custom request headers (excluding automatic browser headers)
    headers = req.get("headers") or req.get("requestHeaders") or {}
    if isinstance(headers, dict):
        custom_headers = {
            k: v for k, v in headers.items()
            if str(k).lower() not in AUTOMATIC_BROWSER_HEADERS
        }
        if custom_headers:
            targets.append(json.dumps(custom_headers))

    return " ".join(targets)


def correlate_apis_and_requests(
    api_events: list[dict[str, Any]],
    network_requests: list[dict[str, Any]],
    raw_api_values: dict[str, list[str]] | None = None,
    max_window_ms: int = 5000,
    allowed_phases: set[str] | None = None,
) -> dict[str, Any]:
    """Correlate browser API events with outgoing network requests conservatively.
    
    Parameters
    ----------
    api_events : list[dict]
        Recorded API events from APICallCollector.
    network_requests : list[dict]
        Recorded network requests from RequestCollector.
    raw_api_values : dict[str, list[str]], optional
        In-memory mapping from api_event_id to captured raw strings (for value matching).
    max_window_ms : int
        Maximum allowed time difference between API event and subsequent request.
    allowed_phases : set[str], optional
        Crawl lifecycle phases permitted for primary analysis (default: page_load & passive).

    Returns
    -------
    dict containing:
    - 'associations': list of association records
    - 'summary': metrics covering unique API events and unique requests linked
    """
    if allowed_phases is None:
        allowed_phases = {"page_load", "passive_ad_delivery", "passive_observation"}

    raw_values = raw_api_values or {}
    associations: list[dict[str, Any]] = []
    assoc_counter = 0

    valid_requests = [r for r in network_requests if isinstance(r, dict) and r.get("timestamp_ms")]
    valid_apis = [a for a in api_events if isinstance(a, dict) and a.get("timestamp_ms")]

    linked_api_ids: set[str] = set()
    linked_request_ids: set[str] = set()
    value_matched_api_ids: set[str] = set()
    value_matched_request_ids: set[str] = set()

    for api in valid_apis:
        api_id = str(api.get("api_event_id") or "")
        api_ts = api["timestamp_ms"]
        api_phase = api.get("phase", "page_load")
        api_script_id = str(api.get("script_id") or "")
        api_script_url = str(api.get("normalized_script_url") or api.get("source_script") or "")
        api_frame_id = str(api.get("frame_id") or "")
        api_parent_frame = str(api.get("parent_frame_id") or "")
        api_doc_id = str(api.get("document_id") or "")

        candidate_raw_vals = raw_values.get(api_id, [])

        for req in valid_requests:
            req_id = str(req.get("requestId") or req.get("id") or "")
            req_ts = req["timestamp_ms"]
            req_phase = req.get("phase", "page_load")
            req_frame_id = str(req.get("frameId") or "")
            req_doc_id = str(req.get("document_id") or "")

            # 1. Temporal ordering and window constraint
            time_diff = req_ts - api_ts
            if time_diff < 0 or time_diff > max_window_ms:
                continue

            # 2. Document match
            document_match = bool(api_doc_id and req_doc_id and api_doc_id == req_doc_id)

            # 3. Phase compatibility
            phase_compat = (api_phase in allowed_phases and req_phase in allowed_phases)

            # 4. Script evidence
            req_script_ids = [str(s) for s in req.get("initiatingScriptIds", []) if s]
            req_init_urls = [str(u) for u in req.get("initiatorUrls", []) if u]

            exact_script_id_match = bool(api_script_id and api_script_id in req_script_ids)
            stack_url_match = bool(api_script_url and any(api_script_url in u or u in api_script_url for u in req_init_urls))
            script_match = exact_script_id_match or stack_url_match

            # 5. Frame evidence
            exact_frame_match = bool(api_frame_id and req_frame_id and api_frame_id == req_frame_id)
            compatible_frame = exact_frame_match or bool(api_parent_frame and api_parent_frame == req_frame_id)
            frame_match = exact_frame_match or compatible_frame

            # Determine evidence level
            if exact_script_id_match and exact_frame_match:
                evidence_type = "exact_script_and_frame"
            elif exact_script_id_match and compatible_frame:
                evidence_type = "exact_script_compatible_frame"
            elif stack_url_match and exact_frame_match:
                evidence_type = "initiator_stack_and_frame"
            elif stack_url_match and compatible_frame:
                evidence_type = "initiator_stack_compatible_frame"
            elif script_match or frame_match:
                evidence_type = "temporal_only_candidate"
            else:
                evidence_type = "unlinked"

            # Qualification for primary analysis
            accepted = (
                evidence_type in {
                    "exact_script_and_frame",
                    "exact_script_compatible_frame",
                    "initiator_stack_and_frame",
                    "initiator_stack_compatible_frame",
                }
                and phase_compat
                and (document_match or not api_doc_id or not req_doc_id)
            )

            # 6. Direct value matching strictly against script-controlled request components
            value_match_type = "no_value_match"
            matched_preview = None

            if candidate_raw_vals:
                script_controlled_text = extract_script_controlled_request_text(req)
                if script_controlled_text:
                    for raw_val in candidate_raw_vals:
                        match_result = test_value_in_text(raw_val, script_controlled_text)
                        if match_result:
                            value_match_type = match_result
                            matched_preview = raw_val[:30]
                            break

            if value_match_type == "no_value_match" and accepted:
                value_match_type = "same_script_subsequent_request"

            ambiguity_reason = None
            rejection_reason = None
            if not document_match and (api_doc_id and req_doc_id):
                ambiguity_reason = "document_mismatch"
            elif not phase_compat:
                ambiguity_reason = f"phase_incompatible:api={api_phase},req={req_phase}"
            elif evidence_type == "temporal_only_candidate":
                ambiguity_reason = "insufficient_initiator_or_frame_evidence"

            if not accepted:
                if not phase_compat:
                    rejection_reason = f"phase_incompatible:api={api_phase},req={req_phase}"
                elif not document_match and (api_doc_id and req_doc_id):
                    rejection_reason = "document_mismatch"
                elif evidence_type == "temporal_only_candidate":
                    rejection_reason = "insufficient_initiator_or_frame_evidence"
                elif evidence_type == "unlinked":
                    rejection_reason = "unlinked_no_script_or_frame_evidence"
                else:
                    rejection_reason = ambiguity_reason or "candidate_rejected"

            assoc_counter += 1
            assoc_record = {
                "association_id": f"assoc_{assoc_counter:04d}",
                "api_event_id": api_id,
                "request_id": req_id,
                "time_difference_ms": time_diff,
                "evidence_type": evidence_type,
                "script_match": script_match,
                "frame_match": frame_match,
                "document_match": document_match,
                "phase_compatibility": phase_compat,
                "accepted_for_primary_analysis": accepted,
                "rejection_reason": rejection_reason,
                "value_match_type": value_match_type,
                "ambiguity_reason": ambiguity_reason,
            }
            if matched_preview and value_match_type in {"exact_value_match", "encoded_value_match", "configured_transformation_match"}:
                assoc_record["matched_value_preview"] = matched_preview

            associations.append(assoc_record)

            if accepted:
                linked_api_ids.add(api_id)
                linked_request_ids.add(req_id)
            if value_match_type in {"exact_value_match", "encoded_value_match", "configured_transformation_match"}:
                value_matched_api_ids.add(api_id)
                value_matched_request_ids.add(req_id)

    # Sort associations deterministically by ranking:
    evidence_rank = {
        "exact_script_and_frame": 1,
        "exact_script_compatible_frame": 2,
        "initiator_stack_and_frame": 3,
        "initiator_stack_compatible_frame": 4,
        "temporal_only_candidate": 5,
        "unlinked": 6,
    }
    associations.sort(
        key=lambda a: (
            0 if a["accepted_for_primary_analysis"] else 1,
            evidence_rank.get(a["evidence_type"], 99),
            a["time_difference_ms"],
        )
    )

    accepted_associations = [a for a in associations if a["accepted_for_primary_analysis"]]
    rejected_candidate_associations = [a for a in associations if not a["accepted_for_primary_analysis"]]

    summary = {
        "total_association_rows": len(associations),
        "primary_associations_count": len(accepted_associations),
        "accepted_associations_count": len(accepted_associations),
        "rejected_candidate_associations_count": len(rejected_candidate_associations),
        "unique_api_events_linked": len(linked_api_ids),
        "unique_requests_linked": len(linked_request_ids),
        "direct_value_matches_count": len(value_matched_api_ids),
        "unique_requests_with_value_matches": len(value_matched_request_ids),
        "same_script_subsequent_requests_count": sum(1 for a in accepted_associations if a["value_match_type"] == "same_script_subsequent_request"),
    }

    return {
        "associations": accepted_associations,
        "accepted_associations": accepted_associations,
        "rejected_candidate_associations": rejected_candidate_associations,
        "all_candidate_associations": associations,
        "summary": summary,
    }
